# Generated by Django 4.0.3 on 2022-03-27 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='isofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
