# Generated by Django 4.0.3 on 2022-03-27 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0002_isofile_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='isofile',
            name='file',
            field=models.FileField(upload_to='media'),
        ),
    ]
