# Generated by Django 4.0.3 on 2022-07-16 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0002_isofile_torrent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='isofile',
            name='file',
            field=models.FileField(blank=True, upload_to='media'),
        ),
    ]
