# Generated by Django 4.0.3 on 2022-07-18 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0003_alter_isofile_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='isofile',
            name='torrent',
            field=models.CharField(default='NoLink', max_length=1000),
        ),
    ]
